### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Slayforfun** [mallrat208/Multifarm-Crops#2]
Installed this mod into the future's edge modpack, which is available through the twitch launcher (previously curse) and i experienced many crashes. Removed 1 block of the multifarm with the circuit board with emerald tubes in it and didnt experience any crashes anymore. The crash log which i had multiple times is included below
[crash-2017-04-19_21.35.10-server.txt](https://github.com/mallrat208/Multifarm-Crops/files/938096/crash-2017-04-19_21.35.10-server.txt)

I was running the farm with 10/10/10 potatos, powered through a lv wire connector and supplied with water through a pipe from immersive engineering

**Comment by mallrat208** [comment]
I know what that problem is, the farm itself is being passed an list of itemstacks with a null value, I had thought I'd compensated for that already. I'll give it another go. 

In the future when posting crashlogs please use either gist or pastebin

**Comment by Slayforfun** [comment]
Will do, good luck and thanks for the effort, really like the idea of this mod

**Comment by mallrat208** [comment]
I'm uploading version 1.1.0 to Curse, when it shows up give it a try.

**Comment by Slayforfun** [comment]
I updated and kept it running for like 15-20 minutes while i was doing some other stuff and it was still running when i got back, so seems good :)

**Comment by mallrat208** [comment]
Yeah, I think It was a poison potato that got you. Most crops only return one item. Except potatoes. the mod literally choked on a poison potato.
