### ISSUE TITLE
Spongeforge server crash 1.10.2

### ISSUE THREAD

**Issue by Liiw** [mallrat208/Multifarm-Crops#3]
Hello!

I included Multifarm-Crops on a 1.10.2 Spongeforge server. I wanted to automate the production of glowstone from Burning Spores. These seeds require a block of soul sand to grow on and additionally a block of glowstone underneath the soulsand. I had to "trick" the multifarm a little, since it did not want to harvest the crops at first (I had to place a block of smooth sandstone as a farming base to clear the error of "no farmland" and the glowstone was placed on the same level afterwards). 

At first, the multifarm started harvesting the crops, but after a few minutes, the server crashed. I am including the server crash report for your viewing:

[crash-2017-04-23_04.24.11-server.txt](https://github.com/mallrat208/Multifarm-Crops/files/949686/crash-2017-04-23_04.24.11-server.txt)

**Comment by mallrat208** [comment]
This was fixed in the 1.1.0 update

**Comment by Liiw** [comment]
I see, apparently I missed that there is a newer version out. Thank you for your reply! I will now close this issue.

**Comment by mallrat208** [comment]
I should look into how the forge update checker thing works, it would help with this situation
