### ISSUE TITLE
Vibrant Alloy Seeds not harvesting, and locks rest of farm out

### ISSUE THREAD

**Issue by illiath** [mallrat208/Multifarm-Crops#4]
With a forestry multi-farm on version 5.2.17.375 (also on .374), with multfarm-crops version 1.1.0, agricraft version 2.0.0-0.8.0-a15, and enderio version 1.10.2-3.1.180 if you plant a vibrant alloy seed, anthing "following" that to the edge of the farm is not harvested, nor is the vibrant alloy seed crop.

Picture up on imgur:- <a href="http://imgur.com/eP8CS2o"><img src="http://i.imgur.com/eP8CS2o.png" title="source: imgur.com" />http://i.imgur.com/eP8CS2o.png</a>

A quick look through the code and I cannot see any reason this is the case at a quick glance however.

I can only presume this is because the crop requires end stone, as if I remove the crop the nether-based crops harvest just fine.

EDIT:
I forgot to mention, this is also with Mystical Agriculture 1.5.1, and the associated agricraft .json files from https://minecraft.curseforge.com/projects/mystical-agricraft?gameCategorySlug=customization&projectID=264440 (If the link doesn't work, it's called Mystical Agricraft and is the json scripts to allow mystical crops to work with agricraft) version of those scripts is 1.1 alpha.

**Comment by mallrat208** [comment]
My initial reaction is to say there's something wrong with the scripts that add in those plants. I've harvested other crops off of End Stone just fine when testing. I'll poke around with it to see if I can reproduce this without using Mystical Agricraft.

In terms of what Multifarm Crops does, I only tell Forestry that Agricraft Crops are a valid block and query if it's fully grown, mature, and able to harvested and pass those drops back off to forestry. There's literally nothing that should cause items to get skipped.

**Comment by illiath** [comment]
Thanks for looking, pulling up a creative world, and it seems to be something do with placement next to "special" farm blocks. For instance, the above picture has the crop growing next to a water block, this seems to sometimes cause the issue. If there is a block placed next to the farm "core" itself, this occurs as well.

Testing on my server, it's really weird, it almost seems to act as if too many of the "special" crops, and that specific crop causes the issue to appear. But exact crop placement definitely impacts if the issue is seen or not.

Given my testing... I'm really unsure if this is something that is related to a "core" forestry problem, rather than an issue with any of the "addon" mods that lead to this path. I have a work-around, for now, as I found a placement in the farm that functions, and know that shuffling crops around seems to sort this as well. I will do further testing in a creative world as I get time and see if I can't pin down the exact thing that trips this over the next few days.

**Comment by illiath** [comment]
After my testing, I am unable to figure out the conditions that cause this to trigger. However, I know that when I add crops to a position in the farm, I need to watch it mature and see if it harvests. If it harvests automatically, then it's good. If it does not harvest automatically I need to remove the crop and it's underlying blocks and move them elsewhere.

I have seen this trigger with any mystical agriculture crop on crops, so at this point I am going with "it's Forestry doing something weird, or Agricraft doing something weird". And seeing as Agricraft is still alpha, I'm thinking this issue can be closed/put on-hold until after an actual Agricraft release to see if it still exists.

**Comment by illiath** [comment]
Update: With the current Agricraft alpha (2.0.0-0.9.0-a16), this occurs even with base agricraft crops.

However, when it happens I get a warning/error in the server log, which I think means this is being caused by an Agricraft bug. :-
```
==================================================
InfinityLib Warning!
==================================================

Cause:
--------------------------------------------------
        An attempt at spawning a bad ItemStack in the world was intercepted!

Relevant Data:
--------------------------------------------------
        - In World: world
        - At Location: BlockPos{x=362, y=63, z=745}
        - ItemStack:
                - Item: <NULL>
                - Amount: <NULL>
                - Meta: <NULL>
                - Tags: <NULL>

Stacktrace:
--------------------------------------------------
        java.lang.Thread.getStackTrace(Thread.java:1552)
        com.infinityraider.infinitylib.utility.WorldHelper.spawnItemInWorld(WorldHelper.java:95)
        com.infinityraider.agricraft.tiles.TileEntityCrop.lambda$onCropLeftClicked$0(TileEntityCrop.java:127)
        com.infinityraider.agricraft.tiles.TileEntityCrop$$Lambda$872/1624947684.accept(Unknown Source)
        com.infinityraider.agricraft.api.plant.IAgriPlant.getFruitsOnHarvest(IAgriPlant.java:269)
        com.infinityraider.agricraft.api.crop.IAgriCrop.lambda$getFruits$0(IAgriCrop.java:115)
        com.infinityraider.agricraft.api.crop.IAgriCrop$$Lambda$825/631735254.accept(Unknown Source)
        java.util.Optional.ifPresent(Optional.java:159)
        com.infinityraider.agricraft.api.crop.IAgriCrop.getFruits(IAgriCrop.java:115)
        com.infinityraider.agricraft.tiles.TileEntityCrop.getDrops(TileEntityCrop.java:144)
        com.infinityraider.agricraft.tiles.TileEntityCrop.onCropLeftClicked(TileEntityCrop.java:127)
        com.infinityraider.agricraft.blocks.BlockCrop.lambda$onBlockClicked$1(BlockCrop.java:99)
        com.infinityraider.agricraft.blocks.BlockCrop$$Lambda$871/162886239.accept(Unknown Source)
        java.util.Optional.ifPresent(Optional.java:159)
        com.infinityraider.agricraft.blocks.BlockCrop.func_180649_a(BlockCrop.java:99)
        net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:196)
        net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631)
        net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40)
        net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10)
        net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        java.util.concurrent.FutureTask.run(FutureTask.java:266)
        net.minecraft.util.Util.func_181617_a(SourceFile:45)
        net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
        net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        java.lang.Thread.run(Thread.java:745)
==================================================
```

**Comment by mallrat208** [comment]
That'd make sense. The entire problem sounds like a desync between the client and the server about where the actual crop is.

In regards to that console output,  I had to actually write a line into MFC to filter out the drops list because it was passing Null ItemStacks

```java
private static List<ItemStack> getCropDrops(TileEntity tileEntity) {
		if(isAgricraftCrop(tileEntity)) {
			TileEntityCrop crop = (TileEntityCrop) tileEntity;
			List<ItemStack> harvestResults;
			harvestResults = new ArrayList<>();
			crop.getFruits((harvestResults::add),random);
			List<ItemStack> filteredList = new ArrayList<>();
			for(ItemStack stack: harvestResults) {
				if(stack!=null) filteredList.add(stack);
			}
			Proxies.common.addBlockDestroyEffects(tileEntity.getWorld(),tileEntity.getPos(),((TileEntityCrop) tileEntity).getState());
			crop.setGrowthStage(0);
			return filteredList.isEmpty()? null: filteredList;
		}
		return null;
	}
```

**Comment by illiath** [comment]
I can confirm, since the new agricraft update, this issue has not resurfaced. However, Agricraft is having some of it's own issues for me since the -17 alpha. I therefore consider this issue resolved as the most recent version of Agrcraft that is otherwise usable for me, works fine with this.

**Comment by mallrat208** [comment]
Great to hear
